### ISSUE TITLE
Criar um pipeline de atualização contínua

### ISSUE THREAD

**Issue by felipefernandes** [CodeClubBrasil/ccbr-gerador-certificados#7]
Isso é um item importante pois vai permitir que possamos atualizar o ambiente de produção sem muita burocracia.

**Comment by felipefernandes** [comment]
Sugestões? TravicCI ?

**Comment by sandrogiacom** [comment]
Posso fazer um teste com o Travis fazendo deploy no Heroku

**Comment by felipefernandes** [comment]
Acho que ia ser maximo!

boto fé nessa integração

Abs

FF


Em sex, 17 de ago de 2018 às 20:08, Sandro Giacomozzi <
notifications@github.com> escreveu:

**Comment by sandrogiacom** [comment]
Após o merge na master, já esta fazendo o deploy no Heroku através do Travis. A versão 0.5 já temos uma API disponível para a geração. Então já pode ser integrado com o portal dos voluntários. Imagem já atualizada no [docker hub](https://hub.docker.com/r/codeclubbrasil/gerador-certificados/)

**Comment by sandrogiacom** [comment]
Pipeline criado fazendo deploy no heroku
